import Head from 'next/head';

export default function Home() {
  return (
    <div className='container'>
      {' '}
      <Head>
        <title>Css is important...</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>First Stage of The Project "Css Layout"</h1>
    </div>
  );
}
